---
apiVersion: v2
appVersion: 1.0.0
description: An image and helm chart for crowdsec-custom-bouncer
name: crowdsec-custom-bouncer
version: 1.0.0
kubeVersion: ">=1.16.0-0"
keywords:
  - crowdsec-custom-bouncer
home: https://github.com/mwinters-stuff/crowdsec-custom-bouncer
sources:
  - https://github.com/crowdsecurity/cs-custom-bouncer
maintainers:
  - name: mwinters
    email: mathew@winters.nz
dependencies:
  - name: common
    repository: oci://harbor.winters.org.nz/k8s-at-winters
    version: 0.1.5
