#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common/values.yaml
#

image:
  # -- image repository
  repository: harbor.winters.org.nz/public/crowdsec-custom-bouncer
  # -- image tag
  tag: "latest"
  # -- image pull policy
  pullPolicy: IfNotPresent

nameOverride: "crowdsec-custom-bouncer"
fullnameOverride: "crowdsec-custom-bouncer"


# @default -- See below
env:
  # -- Set the container timezone
  TZ: Pacific/Auckland
  # -- Set the container user id
  PUID: "1000"
  # -- Set the container group id
  PGID: "1000"

#-- Configures service settings for the chart.
# @default -- See values.yaml
service:
  main:
    enabled: false

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See values.yaml
  main:
    enabled: false

# -- Configure persistence, config for where the yaml and custom script live..
# @default -- See values.yaml
persistence:
  config:
    enabled: false
